ci:
  collect:
    numberOfRuns: 1
    startServerCommand: node server.js
    url:
      - http://localhost:3000/
      - http://localhost:3000/pricing
      - http://localhost:3000/support
  upload:
    target: lhci