name: "Lighthouse"
on:
  push:
    branches:
      - master
jobs:
  build:
      name: Run Lighthouse
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-node@v1
          with:
            node-version: 10.x
        - name: Start server
          run: "npm run serve"
